"""
Setup script for the filemover package.

This script declares a ``console_scripts`` entry point so that the CLI can
be invoked directly after installation.  It is only intended as a minimal
setup script for demonstration purposes; for production use consider
authoring a ``pyproject.toml`` instead.
"""

from setuptools import setup, find_packages


setup(
    name="filemover",
    version="0.1.0",
    description="Move Python files and folders while updating import statements",
    author="Generated by filemover script",
    packages=find_packages(),
    include_package_data=True,
    python_requires=">=3.8",
    install_requires=[
        "click>=7.0",
    ],
    entry_points={
        "console_scripts": [
            "filemover=filemover.cli:main",
        ]
    },
)